humanResourceProject.Presentation/Controllers/JobController.cs
using humanResourceProject.Models.DTOs;
using humanResourceProject.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace humanResourceProject.Presentation.Controllers
{
    [Authorize(Roles = "SiteManager, CompanyManager")]
    public class JobController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;
        public JobController(IConfiguration configuration)
        {
            _configuration = configuration;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_configuration["BaseAddress"]);
        }
        public async Task<IActionResult> Jobs()
        {
            Guid companyId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "CompanyId").Value);

            var response = await _httpClient.GetAsync($"api/Job/GetJobsByCompanyId/{companyId}");

            if (response.IsSuccessStatusCode)
            {
                var jobsResponse = await response.Content.ReadAsStringAsync();
                List<JobVM>? jobsList = JsonConvert.DeserializeObject<List<JobVM>>(jobsResponse);
                return View(jobsList);
            }

            return View("Error");
        }

        public async Task<IActionResult> CreateJob()
        {
            Guid companyId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "CompanyId").Value);

            return View(new JobDTO { CompanyId = companyId });

        }

        [HttpPost]
        public async Task<IActionResult> CreateJob(JobDTO model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("api/Job/CreateJob", content);

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessCreateJobMessage"] = "Şirketinize Pozisyon Eklenmiştir.";
                return RedirectToAction(nameof(Jobs));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu pozisyon adına sahip zaten bir pozisyon var!");
                return View(model);
            }

        }

        [HttpGet]
        public async Task<IActionResult> UpdateJob(Guid id)
        {
            var response = await _httpClient.GetAsync($"api/Job/GetUpdateJobDTO/{id}");

            if (response.IsSuccessStatusCode)
            {
                var jobDTOResponse = await response.Content.ReadAsStringAsync();
                UpdateJobDTO? jobDTO = JsonConvert.DeserializeObject<UpdateJobDTO>(jobDTOResponse);
                return View(jobDTO);
            }

            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateJob(UpdateJobDTO model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Bir hata oluştu tekrar deneyiniz!");
                return View(model);
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync("api/Job/", content);

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessUpdateJobMessage"] = "Pozisyon güncellenmiştir.";
                return RedirectToAction(nameof(Jobs));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu pozisyon adına sahip zaten bir pozisyon var!");
                return View(model);
            }
        }

        public async Task<IActionResult> DeleteJob(Guid id)
        {
            var response = await _httpClient.DeleteAsync($"api/Job/DeleteJob/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessDeleteJobMessage"] = "Pozisyon kaldırılmıştır.";
                return RedirectToAction(nameof(Jobs));
            }

            return View("Error");
        }
    }
}

humanResourceProject.Presentation/Controllers/LeaveController.cs
using humanResourceProject.Domain.Enum;
using humanResourceProject.Models.DTOs;
using humanResourceProject.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using System.Text;

namespace humanResourceProject.Presentation.Controllers
{
    [Authorize]
    public class LeaveController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;

        public LeaveController(IConfiguration configuration)
        {
            _configuration = configuration;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_configuration["BaseAddress"]);
        }

        [Authorize(Roles = "Manager,Personel,CompanyManager")]
        public async Task<IActionResult> MyLeaves()
        {
            Guid employeeId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);

            var response = await _httpClient.GetAsync($"api/Leave/GetLeavesByEmployeeId/{employeeId}");
            if (response.IsSuccessStatusCode)
            {
                var cont = await response.Content.ReadAsStringAsync();
                var leaves = JsonConvert.DeserializeObject<List<LeavePersonnelVM>>(cont);
                return View(leaves);
            }
            return View("Error");
        }

        [Authorize(Roles = "Manager,CompanyManager")]
        public async Task<IActionResult> EmployeesLeaves()
        {
            if(User.IsInRole("Manager") || User.IsInRole("CompanyManager"))
            {
                Guid managerId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);

                var response = await _httpClient.GetAsync($"api/Leave/GetLeavesByManagerId/{managerId}");
                if (response.IsSuccessStatusCode)
                {
                    var cont = await response.Content.ReadAsStringAsync();
                    var leaves = JsonConvert.DeserializeObject<List<LeaveVM>>(cont);
                    return View(leaves);
                }
                return View();
            }
            //else if(User.IsInRole("CompanyManager"))
            //{
            //    Guid companyId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "CompanyId").Value);

            //    var response = await _httpClient.GetAsync($"api/Leave/GetLeavesByCompanyId/{companyId}");
            //    if (response.IsSuccessStatusCode)
            //    {
            //        var cont = await response.Content.ReadAsStringAsync();
            //        var leaves = JsonConvert.DeserializeObject<List<LeaveVM>>(cont);
            //        return View(leaves);
            //    }
            //    return View();
            //}
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateLeave(Guid id)
        {
            var managerId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "ManagerId").Value);

            if (managerId == Guid.Empty)
            {
                TempData["ManagerIdEmptyMessage"] = "Yöneticiniz henüz atanmadığı için şuanda izin ekleyemezsiniz!";
                return RedirectToAction(nameof(MyLeaves));
            }

            var response = await _httpClient.GetAsync($"api/Leave/GetLeaveDTO/{id}");
            if (response.IsSuccessStatusCode)
            {
                var cont = await response.Content.ReadAsStringAsync();
                var leaveDTO = JsonConvert.DeserializeObject<LeaveDTO>(cont);
                return View(leaveDTO);
            }
            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> CreateLeave(LeaveDTO model)
        {

            if (!ModelState.IsValid)
            {
                if (ModelState["LeaveType"].Errors.Count > 0)
                {
                    ModelState.AddModelError(string.Empty, "İzin türünü seçiniz!");
                }
                return View(model);
            }

            if( model.DaysOfLeave > (decimal)(model.EndDateOfLeave - model.StartDateOfLeave).TotalDays)
            {
                ModelState.AddModelError(string.Empty, "Lütfen geçerli bir izin gün sayısı giriniz!");
                return View(model);
            }


            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync($"api/Leave", content);
            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessCreateLeaveMessage"] = "İzin talebiniz oluşturulmuştur.";
                return RedirectToAction(nameof(MyLeaves));
            }
            else
            {
                ModelState.AddModelError(response.StatusCode.ToString(), "Bir hata oluştu.");
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteLeave(Guid id)
        {
            var response = await _httpClient.DeleteAsync($"api/Leave/DeleteLeave/{id}");

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessDeleteLeaveMessage"] = "İzin talebiniz silinmiştir.";
                
                return RedirectToAction(nameof(MyLeaves));
            }
            return View("Error");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateLeave(Guid id)
        {
            var response = await _httpClient.GetAsync($"api/Leave/GetUpdateLeaveDTO/{id}");

            if (response.IsSuccessStatusCode)
            {
                var cont = await response.Content.ReadAsStringAsync();
                var updateLeaveDTO = JsonConvert.DeserializeObject<UpdateLeaveDTO>(cont);
                return View(updateLeaveDTO);
            }
            return View("Error");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateLeave(UpdateLeaveDTO model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Bir hata oluştu tekrar deneyiniz!");
                return View(model);
            }

            if (model.DaysOfLeave > (decimal)(model.EndDateOfLeave - model.StartDateOfLeave).TotalDays)
            {
                ModelState.AddModelError(string.Empty, "Lütfen geçerli bir izin gün sayısı giriniz!");
                return View(model);
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync($"api/Leave", content);

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessUpdateLeaveMessage"] = "İzin talebiniz güncellenmiştir.";
                return RedirectToAction(nameof(MyLeaves));
            }
            else
            {
                ModelState.AddModelError("ModelInvalid", "Girilen bilgileri kontrol edin. Güncelleme başarısız!");
                return View(model);
            }
        }

        //LEAVE REQUESTS & CONTROLS
        [Authorize(Roles = "Manager,CompanyManager")]
        [HttpGet]
        public async Task<IActionResult> ApproveLeave(Guid id)
        {
            var response = await _httpClient.GetAsync($"api/Leave/GetUpdateLeaveDTO/{id}");

            if (!response.IsSuccessStatusCode)
                return View("Error");

            var content = await response.Content.ReadAsStringAsync();
            var model = JsonConvert.DeserializeObject<UpdateLeaveDTO>(content);
            model.LeaveStatus = RequestStatus.Approved;

            var json = JsonConvert.SerializeObject(model);
            var contentDTO = new StringContent(json, Encoding.UTF8, "application/json");

            var httpResponse = await _httpClient.PutAsync($"api/Leave/UpdateStatus", contentDTO);

            if (httpResponse.IsSuccessStatusCode)
            {
                TempData["SuccessApproveLeave"] = "Personelinizin izin talebini onayladınız.";
                return RedirectToAction(nameof(EmployeesLeaves));
            }
            ModelState.AddModelError(httpResponse.StatusCode.ToString(), "Bir hata oluştu.");
            return View("Error");
        }

        [Authorize(Roles = "Manager,CompanyManager")]
        [HttpPost]
        public async Task<IActionResult> RejectLeave(Guid id, string rejectReason)
        {
            var response = await _httpClient.GetAsync($"api/Leave/GetUpdateLeaveDTO/{id}");

            if (!response.IsSuccessStatusCode)
                return View("Error");
            
            var content = await response.Content.ReadAsStringAsync();
            var model = JsonConvert.DeserializeObject<UpdateLeaveDTO>(content);
            model.LeaveStatus = RequestStatus.Rejected;
            model.RejectReason = rejectReason;

            var json = JsonConvert.SerializeObject(model);
            var contentDTO = new StringContent(json, Encoding.UTF8, "application/json");

            var httpResponse = await _httpClient.PutAsync($"api/Leave/UpdateStatus", contentDTO);

            if (httpResponse.IsSuccessStatusCode)
            {
                return Ok("success");
            }
            ModelState.AddModelError(httpResponse.StatusCode.ToString(), "Bir hata oluştu.");
            return View("Error");
        }
    }
}

humanResourceProject.Presentation/Views/Shared/_ErrorLayout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Monitorease - @ViewData["Title"]</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/humanResourceProject.Presentation.styles.css" asp-append-version="true" />

</head>
<body>
    @RenderBody()
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

humanResourceProject.Presentation/Views/Shared/_PanelPartial.cshtml
@using System.Security.Claims;

<div class="panel col-md-1 col-lg-1">
    <button class="btn btn-sm float-end border-0 toggle-sidepanel" style="background-color:#A0AAFF;" onclick="hidePanel()"><i class="fa-solid fa-arrow-left"></i></button>

    <div class="profile row">
        <div class="picture">
            <input type="file" id="uploadInput" style="display: none;" />
            <img id="profileImg" src="@(User.Claims.FirstOrDefault(x => x.Type == "ImagePath").Value)" alt="profileImage" title="Profil Fotoğrafını Güncelle" />
        </div>
        <div class="name text-center">
            <h3>@(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value + " " + User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Surname).Value)</h3>
        </div>
    </div>

    <div class="ul">

        <div class="panel-items">
            <ul class="panel-list">
                <li>
                    <a asp-action="Home" asp-controller="Employee"><i class="fa-solid fa-calendar-days"></i>Dashboard</a>
                </li>
                @if (!User.IsInRole("SiteManager"))
                {
                    <li class="parent">
                        <a href="#"><i class="fa-solid fa-hand-holding"></i>Taleplerim</a>
                        <ul class="sub-menu">
                            <li>
                                <a asp-action="MyLeaves" asp-controller="Leave"><i class="fa-solid fa-person-walking-luggage"></i> İzin Taleplerim</a>
                            </li>
                            <li>
                                <a asp-action="MyAdvances" asp-controller="Advance"><i class="fa-solid fa-sack-dollar"></i> Avans Taleplerim</a>
                            </li>
                            <li>
                                <a asp-action="MyExpenses" asp-controller="Expense"><i class="fa-solid fa-file-invoice-dollar"></i> Masraf Taleplerim</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="MyPossessions" asp-controller="Possession"><i class="fa-solid fa-building-shield"></i>Zimmetlerim</a>
                    </li>
                    <li>
                        <a asp-action="Employees" asp-controller="Employee"><i class="fa fa-users"></i>Personeller</a>
                    </li>
                }
                @if (User.IsInRole("CompanyManager") || User.IsInRole("Manager"))
                {

                    <li class="parent">
                        <a href="#"><i class="fa-solid fa-person-circle-exclamation"></i>Personel Talepleri</a>
                        <ul class="sub-menu">
                            <li>
                                <a asp-action="EmployeesLeaves" asp-controller="Leave"><i class="fa-solid fa-person-walking-luggage"></i> Personel İzin Talepleri</a>
                            </li>
                            <li>
                                <a asp-action="EmployeesAdvances" asp-controller="Advance"><i class="fa-solid fa-sack-dollar"></i> Personel Avans Talepleri</a>
                            </li>
                            <li>
                                <a asp-action="EmployeesExpenses" asp-controller="Expense"><i class="fa-solid fa-file-invoice-dollar"></i> Personel Masraf Talepleri</a>
                            </li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("CompanyManager"))
                {
                    <li>
                        <a asp-action="Departments" asp-controller="Department"><i class="fa-solid fa-building-user"></i>Departmanlar</a>
                    </li>
                    <li>
                        <a asp-action="Jobs" asp-controller="Job"><i class="fa-solid fa-briefcase"></i>Pozisyonlar</a>
                    </li>
                    <li>
                        <a asp-action="Possessions" asp-controller="Possession"><i class="fa-solid fa-building-shield"></i>Zimmetler</a>
                    </li>

                }

                @if (User.IsInRole("SiteManager"))
                {
                    <li>
                        <a asp-action="Companies" asp-controller="Company"><i class="fa-solid fa-building-user"></i>Şirketler</a>
                    </li>
                }

                @* <li>
                <a href="#"><i class="fa fa-newspaper"></i>Raporlar</a>
                </li>
                <li>
                <a href="#"><i class="fa fa-calendar"></i>Takvim</a>
                </li>
                <li>
                <a href="#"><i class="fa fa-envelope"></i>E-posta</a>
                </li> *@

            </ul>
        </div>
    </div>
    <div class="log-out-button text-center">

        <a asp-controller="Account" asp-action="Logout" class="custom-button custom-button--logout">Çıkış Yap</a>
    </div>

</div>

@*PANELICONS*@

<div class="panelIcons col-md-1 col-lg-1">
    <button class="btn btn-sm border-0 " style="background-color:#A0AAFF;margin-left:1vw;" onclick="showPanel()"><i class="fa-solid fa-arrow-right " style="font-size: 16px;"></i></button>
    <div class="ul">

        <div class="panel-items-icons">
            <ul class="panel-list">
                <li>
                    <a data-toggle="tooltip" title="Dashboard" asp-action="Home" asp-controller="Employee"><i class="fa-solid fa-calendar-days"></i></a>
                </li>
                @if (User.IsInRole("Personel") || User.IsInRole("Manager"))
                {
                    <li class="parent">
                        <a data-toggle="tooltip" title="Taleplerim" href="#"><i class="fa-solid fa-hand-holding"></i></a>
                        <ul class="sub-menu">
                            <li>
                                <a data-toggle="tooltip" title="İzinlerim" asp-action="MyLeaves" asp-controller="Leave"><i class="fa-solid fa-person-walking-luggage"></i></a>
                            </li>
                            <li>
                                <a data-toggle="tooltip" title="Avanslarım" asp-action="MyAdvances" asp-controller="Advance"><i class="fa-solid fa-sack-dollar"></i></a>
                            </li>
                            <li>
                                <a data-toggle="tooltip" title="Masraflarım" asp-action="MyExpenses" asp-controller="Expense"><i class="fa-solid fa-file-invoice-dollar"></i></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a data-toggle="tooltip" title="Zimmetlerim" asp-action="MyPossessions" asp-controller="Possession"><i class="fa-solid fa-building-shield"></i></a>
                    </li>
                }
                @if (!User.IsInRole("SiteManager"))
                {
                    <li>
                        <a data-toggle="tooltip" title="Personeller" asp-action="Employees" asp-controller="Employee"><i class="fa fa-users"></i></a>
                    </li>
                }
                @if (User.IsInRole("CompanyManager") || User.IsInRole("Manager"))
                {

                    <li class="parent">
                        <a data-toggle="tooltip" title="Personel Talepleri" href="#"><i class="fa-solid fa-person-circle-exclamation"></i></a>
                        <ul class="sub-menu">
                            <li>
                                <a data-toggle="tooltip" title="İzin Talepleri" asp-action="EmployeesLeaves" asp-controller="Leave"><i class="fa-solid fa-person-walking-luggage"></i></a>
                            </li>
                            <li>
                                <a data-toggle="tooltip" title="Avans Talepleri" asp-action="EmployeesAdvances" asp-controller="Advance"><i class="fa-solid fa-sack-dollar"></i></a>
                            </li>
                            <li>
                                <a data-toggle="tooltip" title="Masraf Talepleri" asp-action="EmployeesExpenses" asp-controller="Expense"><i class="fa-solid fa-file-invoice-dollar"></i></a>
                            </li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("CompanyManager"))
                {
                    <li>
                        <a data-toggle="tooltip" title="Departmanlar" asp-action="Departments" asp-controller="Department"><i class="fa-solid fa-building-user"></i></a>
                    </li>
                    <li>
                        <a data-toggle="tooltip" title="Pozisyonlar" asp-action="Jobs" asp-controller="Job"><i class="fa-solid fa-briefcase"></i></a>
                    </li>
                    <li>
                        <a data-toggle="tooltip" title="Zimmetler" asp-action="Possessions" asp-controller="Possession"><i class="fa-solid fa-building-shield"></i></a>
                    </li>
                }

                @if (User.IsInRole("SiteManager"))
                {
                    <li>
                        <a data-toggle="tooltip" title="Şirketler" asp-action="Companies" asp-controller="Company"><i class="fa-solid fa-building-user"></i></a>
                    </li>
                }

                @* <li>
                <a data-toggle="tooltip" title="Raporlar" href="#"><i class="fa fa-newspaper"></i></a>
                </li>
                <li>
                <a data-toggle="tooltip" title="Takvim" href="#"><i class="fa fa-calendar"></i></a>
                </li>
                <li>
                <a data-toggle="tooltip" title="E-posta" href="#"><i class="fa fa-envelope"></i></a>
                </li> *@

            </ul>
        </div>
    </div>
</div>

<script>
    //Açılır kapanır panel menu

    $(document).ready(function () {
        $(".sub-menu").hide();

        $(".parent > a").click(function (event) {
            event.preventDefault();
            var subMenu = $(this).siblings(".sub-menu");
            $(".sub-menu").not(subMenu).slideUp();
            subMenu.slideToggle();
        });

        $(document).click(function (event) {
            if (!$(event.target).closest('.parent').length) {
                $(".sub-menu").slideUp();
            }
        });
    });


    // Profile image upload
    $(document).ready(function () {
        $('#profileImg').on('click', function () {
            $('#uploadInput').click(); // Trigger file input click on image click
        });

        $('#uploadInput').on('change', function (e) {
            var file = e.target.files[0];
            if (!file) return;

            var formData = new FormData();
            formData.append('Id', 'UserId'); // Replace with the user ID
            formData.append('UploadPath', file);

            $.ajax({
                url: '/Account/UpdateProfileImage',
                type: 'POST',
                processData: false,
                contentType: false,
                data: formData,
                success: function (response) {
                    // Assuming the response is the updated image path from the server
                    var imagePath = response.imageUrl;
                    $('#profileImg').attr('src', imagePath);
                    console.log('Profile image updated successfully');
                },
                error: function (xhr, status, error) {
                    console.error('Error updating profile image:', error);
                }
            });
        });
    });

    //sol panel gizleme & gösterme

    function hidePanel() {
        var panels = document.getElementsByClassName("panel");
        var panelIcons = document.getElementsByClassName("panelIcons");
        var aside = document.getElementsByClassName("aside")[0];

        for (var i = 0; i < panels.length; i++) {
            panels[i].style.display = "none";
        }

        for (var j = 0; j < panelIcons.length; j++) {
            panelIcons[j].style.display = "block";
        }

        aside.style.width = "90%";
        localStorage.setItem('panelState', 'hidden');
    };

    function showPanel() {
        var panels = document.getElementsByClassName("panel");
        var panelIcons = document.getElementsByClassName("panelIcons");
        var aside = document.getElementsByClassName("aside")[0];

        for (var i = 0; i < panels.length; i++) {
            panels[i].style.display = "block";
        }

        for (var j = 0; j < panelIcons.length; j++) {
            panelIcons[j].style.display = "none";
        }
        aside.style.width = "80%";
        localStorage.setItem('panelState', 'visible');
    }

    window.onload = function () {
        var panelState = localStorage.getItem('panelState');

        if (panelState === 'hidden') {
            hidePanel();
        } else {
            showPanel();
        }
    }

    //bootstrap tooltip
    $(function () {
        $('[data-toggle="tooltip"]').tooltip({
            placement: 'right'
        })
    })



</script>