humanResourceProject.Presentation/Controllers/PossessionController.cs
using humanResourceProject.Models.DTOs;
using humanResourceProject.Models.VMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using System.Text;

namespace humanResourceProject.Presentation.Controllers
{
    [Authorize(Roles = "SiteManager, CompanyManager, Manager, Personel")]
    public class PossessionController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;
        public PossessionController(IConfiguration configuration)
        {
            _configuration = configuration;
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(_configuration["BaseAddress"]);
        }
        public async Task<IActionResult> Possessions()
        {
            Guid companyId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "CompanyId").Value);


            var response = await _httpClient.GetAsync($"api/Possession/GetPossessionsByCompanyId/{companyId}");

            if (response.IsSuccessStatusCode)
            {
                var possessionsResponse = await response.Content.ReadAsStringAsync();
                List<PossessionVM>? possessionsList = JsonConvert.DeserializeObject<List<PossessionVM>>(possessionsResponse);

                var json = JsonConvert.SerializeObject(companyId);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var responseEmployee = await _httpClient.PostAsync($"api/AppUser/GetEmployeesByCompanyId/", content);
                if (responseEmployee.IsSuccessStatusCode)
                {
                    var employeesContent = await responseEmployee.Content.ReadAsStringAsync();
                    var employees = JsonConvert.DeserializeObject<List<PersonelVM>>(employeesContent);

                    ViewBag.Employees = employees;

                    return View(possessionsList);
                }
            }
            return View("Error");
        }

        [Authorize(Roles = "Manager, Personel, CompanyManager")]
        public async Task<IActionResult> MyPossessions()
        {
            Guid employeeId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
            var response = await _httpClient.GetAsync($"api/Possession/GetPossessionsByEmployeeId/{employeeId}");

            if (response.IsSuccessStatusCode)
            {
                var possessionsResponse = await response.Content.ReadAsStringAsync();
                List<PersonelPossessionVM>? possessionsList = JsonConvert.DeserializeObject<List<PersonelPossessionVM>>(possessionsResponse);

                return View(possessionsList);
            }
            return View("Error");
        }


        [Authorize(Roles = "CompanyManager")]
        public async Task<IActionResult> CreatePossession()
        {
            Guid companyId = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "CompanyId").Value);

            return View(new PossessionDTO { CompanyId = companyId });

        }

        [Authorize(Roles = "CompanyManager")]
        [HttpPost]
        public async Task<IActionResult> CreatePossession(PossessionDTO model)
        {
            if (!ModelState.IsValid)
            {
                if (ModelState["PossessionType"].Errors.Count > 0)
                {
                    ModelState.AddModelError(string.Empty, "Zimmet türünü seçiniz!");
                }
                return View(model);
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("api/Possession/CreatePossession", content);

            if (response.IsSuccessStatusCode)
            {
                TempData["CreatePossessionMessage"] = "Zimmet başarıyla oluşturuldu.";
                return RedirectToAction(nameof(Possessions));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu barkod numarasına sahip zaten bir zimmet var!");
                return View(model);
            }

        }

        //public async Task<IActionResult> DetailsPossession(Guid id)
        //{
        //    var response = await _httpClient.GetAsync($"api/Possession/DetailsPossession/{id}");

        //    if (response.IsSuccessStatusCode)
        //    {
        //        var possessionDetailResponse = await response.Content.ReadAsStringAsync();
        //        PossessionVM? possessionVM = JsonConvert.DeserializeObject<PossessionVM>(possessionDetailResponse);
        //        return View(possessionVM);
        //    }

        //    return View("Error");
        //}

        [Authorize(Roles = "CompanyManager")]
        public async Task<IActionResult> UpdatePossession(Guid id)
        {
            var response = await _httpClient.GetAsync($"api/Possession/GetUpdatePossessionDTO/{id}");

            if (response.IsSuccessStatusCode)
            {
                var possessionDTOResponse = await response.Content.ReadAsStringAsync();
                UpdatePossessionDTO? possessionDTO = JsonConvert.DeserializeObject<UpdatePossessionDTO>(possessionDTOResponse);
                return View(possessionDTO);
            }

            return View("Error");
        }

        [Authorize(Roles = "CompanyManager")]
        [HttpPost]
        public async Task<IActionResult> UpdatePossession(UpdatePossessionDTO model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Bir hata oluştu tekrar deneyiniz!");
                return View(model);
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync("api/Possession/", content);

            if (response.IsSuccessStatusCode)
            {
                TempData["SuccessUpdatePossesionMessage"] = "Zimmet güncellenmiştir.";
                return RedirectToAction(nameof(Possessions));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu barkod numarasına sahip zaten bir zimmet var!");
                return View(model);
            }
        }

        [Authorize(Roles = "CompanyManager")]
        public async Task<IActionResult> DeletePossession(Guid id)
        {
            var response = await _httpClient.DeleteAsync($"api/Possession/DeletePossession/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Possessions));
            }

            return View("Error");
        }

        [Authorize(Roles = "CompanyManager")]
        [HttpPost]
        public async Task<IActionResult> AssignPossession(Guid employeeId, Guid itemId)
        {
            AssignPossessionDTO assignPossessionDTO = new AssignPossessionDTO
            {
                EmployeeId = employeeId,
                PossessionId = itemId
            };
            var json = JsonConvert.SerializeObject(assignPossessionDTO);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("api/Possession/AssignPossession", content);

            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true, message = "Zimmet atama işleminiz başarılı bir şekilde gerçekleşmiştir." });
            }
            return Json(new { success = false, message = "Zimmet atama işleminiz başarısız." });
        }

        [Authorize(Roles = "CompanyManager")]
        public async Task<IActionResult> TakeBackPossession(Guid id)
        {
            var json = JsonConvert.SerializeObject(id);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync($"api/Possession/TakeBackPossession/", content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Possessions));
            }

            return View("Error");
        }
    }
}

humanResourceProject.Presentation/Views/Possession/CreatePossession.cshtml
@model PossessionDTO

@{
    ViewData["Title"] = "CreatePossession";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}
<style>
    ul {
        list-style-type: none;
        padding: 0;
    }
</style>

<body>
    <div class="row">
        @Html.Partial("_PanelPartial")

        <div class="col-md-4" style="margin: 35px auto">
            <form asp-action="CreatePossession" asp-controller="Possession" method="post">
                <div class="card shadow p-3 mb-5 bg-body rounded">
                    <div class="card-header">
                        <h1 class="card-title text-center">YENİ ZİMMET EKLE</h1>
                    </div>
                    <div class="card-body">
                        <div class="form-group mb-3">
                            <label asp-for="Barcode" class="control-label"></label>
                            <input id="Barcode" oninput="limitCharacters()" asp-for="Barcode" class="form-control" />
                            <input id="charCount" type="hidden"></input>
                            <p id="charLimitMessage" style="color: red;"></p>
                            <span asp-validation-for="Barcode" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Brand" class="control-label"></label>
                            <input id="Brand" oninput="limits()" asp-for="Brand" class="form-control" />
                            <input id="Count" type="hidden"></input>
                            <p id="LimitMessage" style="color: red;"></p>
                            <span asp-validation-for="Brand" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="PossessionModel" class="control-label"></label>
                            <input id="PossessionModel" oninput="limitChar()" asp-for="PossessionModel" class="form-control" />
                            <input id="charC" type="hidden"></input>
                            <p id="Message" style="color: red;"></p>
                            <span asp-validation-for="PossessionModel" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="PossessionType" class="control-label"></label>
                            <select asp-for="PossessionType" class="form-control">
                                @{
                                    var enumType = typeof(PossessionType);
                                    var enumValues = enumType.GetEnumValues();

                                    foreach (var enumValue in enumValues)
                                    {
                                        var displayAttribute = enumType.GetMember(enumValue.ToString())[0].GetCustomAttribute<DisplayAttribute>();
                                        var displayName = displayAttribute?.GetName() ?? enumValue.ToString();

                                        <option value="@enumValue">@displayName</option>
                                    }
                                    <option value="-1" selected>Zimmet Türü seçiniz!</option>
                                }

                            </select>
                            @* <span asp-validation-for="PossessionType" class="text-danger"></span> *@
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Details" class="control-label"></label>
                            <textarea id="Details" oninput="limit()" asp-for="Details" class="form-control" rows="8"></textarea>
                            <input id="char" type="hidden"></input>
                            <p id="MessageL" style="color: red;"></p>
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <input asp-for="CompanyId" type="hidden" class="form-control" />
                        </div>
                        <div class="mb-3">
                            <label>*Zorunlu alan</label>
                        </div>

                        <div class="form-group mb-3 d-grid">
                            <input type="submit" value="Ekle" class="btn-submit" />
                        </div>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        function limitCharacters() {
            var inputElement = document.getElementById('Barcode');
            var charCountElement = document.getElementById('charCount');
            var charLimitMessageElement = document.getElementById('charLimitMessage');

            var maxCharacters = 50; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
    <script>
        function limits() {
            var inputElement = document.getElementById('Brand');
            var charCountElement = document.getElementById('Count');
            var charLimitMessageElement = document.getElementById('LimitMessage');

            var maxCharacters = 50;

            var enteredText = inputElement.value;
            var Count = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + Count;

            if (Count == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';

            } else {
                charLimitMessageElement.innerText = '';
            }
        }

    </script>
    <script>
        function limitChar() {
            var inputElement = document.getElementById('PossessionModel');
            var charCountElement = document.getElementById('charC');
            var charLimitMessageElement = document.getElementById('Message');

            var maxCharacters = 50; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
    <script>
        function limit() {
            var inputElement = document.getElementById('Details');
            var charCountElement = document.getElementById('char');
            var charLimitMessageElement = document.getElementById('MessageL');

            var maxCharacters = 250; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
</body>

humanResourceProject.Presentation/Views/Possession/DetailsPossession.cshtml
@model PossessionVM

@{
    ViewData["Title"] = "DetailsPossession";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

humanResourceProject.Presentation/Views/Possession/MyPossessions.cshtml
@model List<PersonelPossessionVM>

@{
    ViewData["Title"] = "Possessions";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<body>
    <div class="row">
        @Html.Partial("_PanelPartial")

        <div class="aside container mt-5 col-md-9 col-sm-9">
            <h3 class="heading-list">ZİMMETLERİM</h3>


            <div class="pagination-container">

                <script>
                    var columnsToExport = [0, 1, 2, 3, 4, 5];

                    $(document).ready(function () {
                        $('#possessions').DataTable({
                            "language": {
                                "buttons": {
                                    "copyTitle": "Panoya Kopyalandı",
                                    "copySuccess": {
                                        "_": "%d satır kopyalandı",
                                        "1": "1 satır kopyalandı"
                                    }
                                },
                                "url": "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Turkish.json"
                            },



                            dom: 'lBfrtip',
                            "buttons": [
                                'spacer',
                                {
                                    extend: 'copy',
                                    text: 'Kopyala',

                                },
                                {
                                    extend: 'print',
                                    text: 'Yazdır',
                                    exportOptions: {
                                        columns: columnsToExport
                                    },
                                    //TODO cardviewda görünmesi için tablolarda headerlar var bunların yazdırılmaması gerekir


                                },
                                {
                                    extend: 'spacer',
                                    style: 'bar',
                                    text: 'Dışarı Aktar:'
                                },

                                {
                                    extend: 'csv',
                                    text: 'CSV',
                                    exportOptions: {
                                        columns: columnsToExport
                                    }
                                },
                                {
                                    extend: 'excel',
                                    text: 'Excel',
                                    exportOptions: {
                                        columns: columnsToExport
                                    }
                                },
                                {
                                    extend: 'pdf',
                                    text: 'Pdf',
                                    orientation: 'landscape',
                                    exportOptions: {
                                        columns: columnsToExport
                                    }
                                },

                            ],
                            "order": [
                                [1, 'asc']
                            ],
                        });
                    });
                </script>

                <table id="possessions"
                       class="display">
                    <thead>
                        <tr>
                            <th style="width: 10%">Barkod No</th>
                            <th style="width: 10%">Başlangıç Tarihi</th>
                            <th style="width: 10%">Marka</th>
                            <th style="width: 15%">Model</th>
                            @* <th style="width: 10%">Bitiş Tarihi</th> *@
                            <th style="width: 35%">Açıklama</th>
                            <th style="width: 10%">Zimmet Türü</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    var displayAttribute = typeof(PossessionType).GetMember(item.PossessionType.ToString())[0].GetCustomAttribute<DisplayAttribute>();
                                    var displayName = displayAttribute?.GetName() ?? item.PossessionType.ToString();

                                    <tr>
                                        <td>@item.Barcode</td>
                                    <td>@item.StartDateOfPossession.ToShortDateString()</td>
                                        <td>@item.Brand</td>
                                        <td>@item.PossessionModel</td>
                                        @* <td>@item.EndDateOfPossession.ToShortDateString()</td> *@
                                        <td>@item.Details</td>
                                        <td>@displayName</td>
                                    </tr>
                                }
                            }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

humanResourceProject.Presentation/Views/Possession/UpdatePossession.cshtml
@model UpdatePossessionDTO

@{
    ViewData["Title"] = "UpdatePossession";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}
<head>


    <style>
        ul {
            list-style-type: none;
            padding: 0;
        }
    </style>
</head>
<body>
    <div class="row">
        @Html.Partial("_PanelPartial")

        <div class="col-md-4" style="margin: 35px auto">
            <form asp-action="UpdatePossession" asp-controller="Possession" method="post">
                <div class="card shadow p-3 mb-5 bg-body rounded">
                    <div class="card-header">
                        <h1 class="card-title text-center">ZİMMET GÜNCELLE</h1>
                    </div>
                    <div class="card-body">

                        <div class="form-group mb-3">
                            <label asp-for="Barcode" class="control-label"></label>
                            <input id="Barcode" oninput="limitCharacters()" value="@Model.Barcode" asp-for="Barcode" class="form-control" />
                            <input id="charCount" type="hidden"></input>
                            <p id="charLimitMessage" style="color: red;"></p>
                            <span asp-validation-for="Barcode" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Brand" class="control-label"></label>
                            <input id="Brand" oninput="limits()" value="@Model.Brand" asp-for="Brand" class="form-control" />
                            <input id="Count" type="hidden"></input>
                            <p id="LimitMessage" style="color: red;"></p>
                            <span asp-validation-for="Brand" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="PossessionModel" class="control-label"></label>
                            <input id="PossessionModel" oninput="limitChar()" value="@Model.PossessionModel" asp-for="PossessionModel" class="form-control" />
                            <input id="charC" type="hidden"></input>
                            <p id="Message" style="color: red;"></p>
                            <span asp-validation-for="PossessionModel" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="PossessionType" class="control-label"></label>
                            <select asp-for="PossessionType" class="form-control">
                                @{
                                    var enumType = typeof(PossessionType);
                                    var enumValues = enumType.GetEnumValues();

                                    foreach (var enumValue in enumValues)
                                    {
                                        var displayAttribute = enumType.GetMember(enumValue.ToString())[0].GetCustomAttribute<DisplayAttribute>();
                                        var displayName = displayAttribute?.GetName() ?? enumValue.ToString();

                                        <option value="@enumValue">@displayName</option>
                                    }
                                    <option value="" disabled>Zimmet Türü seçiniz!</option>
                                }

                            </select>
                            <span asp-validation-for="PossessionType" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Details" class="control-label"></label>
                            <textarea id="Details" oninput="limit()" value="@Model.Details" asp-for="Details" class="form-control" rows="8"></textarea>
                            <input id="char" type="hidden"></input>
                            <p id="MessageL" style="color: red;"></p>
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-3">
                            <input value="@Model.CompanyId" asp-for="CompanyId" type="hidden" class="form-control" />
                        </div>
                        <div class="mb-3">
                            <label>*Zorunlu alan</label>
                        </div>

                        <div class="form-group mb-3 d-grid">
                            <input type="submit" value="Güncelle" class="btn-submit" />
                        </div>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        function limitCharacters() {
            var inputElement = document.getElementById('Barcode');
            var charCountElement = document.getElementById('charCount');
            var charLimitMessageElement = document.getElementById('charLimitMessage');

            var maxCharacters = 50; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
    <script>
        function limits() {
            var inputElement = document.getElementById('Brand');
            var charCountElement = document.getElementById('Count');
            var charLimitMessageElement = document.getElementById('LimitMessage');

            var maxCharacters = 50;

            var enteredText = inputElement.value;
            var Count = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + Count;

            if (Count == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';

            } else {
                charLimitMessageElement.innerText = '';
            }
        }

    </script>
    <script>
        function limitChar() {
            var inputElement = document.getElementById('PossessionModel');
            var charCountElement = document.getElementById('charC');
            var charLimitMessageElement = document.getElementById('Message');

            var maxCharacters = 50; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
    <script>
        function limit() {
            var inputElement = document.getElementById('Details');
            var charCountElement = document.getElementById('char');
            var charLimitMessageElement = document.getElementById('MessageL');

            var maxCharacters = 250; // Maksimum karakter sayısını belirle

            var enteredText = inputElement.value;
            var charCount = maxCharacters - enteredText.length;

            charCountElement.innerText = 'Kalan Karakter Sayısı: ' + charCount;

            if (charCount == 0) {
                inputElement.value = enteredText.slice(0, maxCharacters);
                charLimitMessageElement.innerText = 'Maksimum karakter sayısına ulaşıldı!';
            } else {
                charLimitMessageElement.innerText = '';
            }
        }
    </script>
</body>